import { trpc } from "@/utils/trpc";
import { type NextPage } from "next";
import Head from "next/head";
import type { FormEvent } from "react";

const Home: NextPage = () => {
  const { mutate } = trpc.auth.passwordEmail.useMutation();
  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const form = Object.fromEntries(data.entries());
    if (form.email) {
      mutate({ email: String(form.email) });
    }
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-slate-100 ">
        <div className="w-full rounded-lg bg-white px-6 py-4  shadow-md sm:max-w-md">
          <div className="mb-4 text-sm text-gray-600">
            Forgot your password? No problem. Just let us know your email
            address and we will email you a password reset link that will allow
            you to choose a new one.
          </div>
          <form onSubmit={onSubmit}>
            <div>
              <label
                className="block text-sm font-medium text-gray-700"
                htmlFor="email"
              >
                Email
              </label>
              <input
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="email"
                type="email"
                name="email"
              />
            </div>

            <div className="mt-4 flex items-center justify-end">
              <button
                type="submit"
                className="inline-flex items-center rounded-md border border-transparent bg-gray-800 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white transition hover:bg-gray-700 focus:border-gray-900 focus:outline-none focus:ring focus:ring-gray-300 active:bg-gray-900 disabled:opacity-25"
              >
                Email Password Reset Link
              </button>
            </div>
          </form>
        </div>
      </main>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flexa flex-col items-center justify-center gap-12 px-4 py-16 ">

        </div>
      </main> */}
    </>
  );
};

// export function getServerSideProps() {
//   console.log("this is the server");
//   return { props: {} };
// }

export default Home;
