import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import type { FormEvent } from "react";

/**
 *
 * Show inputs (email + password)
 * Show form
 * have a a button that submits
 *
 */

const Home: NextPage = () => {
  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    console.log("form submited");
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-slate-500 ">
        <div className="w-full rounded-lg bg-white px-8 py-6  shadow-sm sm:max-w-md">
          <form onSubmit={onSubmit}>
            <div>
              <label
                className="block text-sm font-medium text-gray-700"
                htmlFor="name"
              >
                Name
              </label>
              <input
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="name"
                type="text"
                name="name"
              />
            </div>
            <div className="mt-4">
              <label
                className="block text-sm font-medium text-gray-700"
                htmlFor="email"
              >
                Email
              </label>
              <input
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="email"
                type="email"
                name="email"
              />
            </div>

            <div className="mt-4">
              <label
                className="block text-sm font-medium text-gray-700"
                htmlFor="password"
              >
                Password
              </label>
              <input
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="password"
                type="password"
                name="password"
              />
            </div>
            <div className="mt-4">
              <label
                className="block text-sm font-medium text-gray-700"
                htmlFor="confirm-password"
              >
                Confirm password
              </label>
              <input
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                id="confirm-password"
                type="password"
                name="confirm_password"
              />
            </div>

            <div className="mt-8 flex items-center justify-end">
              <button
                type="submit"
                className="inline-flex w-full items-center justify-center rounded-md border border-transparent bg-gray-800 px-4 py-2 text-center text-xs font-semibold uppercase tracking-widest text-white transition hover:bg-gray-700 focus:border-gray-900 focus:outline-none focus:ring  focus:ring-gray-300 active:bg-gray-900 disabled:opacity-25"
              >
                <span>Register</span>
              </button>
            </div>
            <div className="mt-4 text-center">
              <Link
                className="text-sm text-gray-500 hover:text-gray-900"
                href="/auth/login"
              >
                Login
              </Link>
            </div>
            <div className="mt-4 text-center">
              <Link
                className="text-sm text-gray-500 hover:text-gray-900"
                href="/auth/forget-password"
              >
                Forgot password?
              </Link>
            </div>
          </form>
        </div>
      </main>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

        </div>
      </main> */}
    </>
  );
};

// export function getServerSideProps() {
//   console.log("this is the server");
//   return { props: {} };
// }

export default Home;
